/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32f407xx.h"
#include "GPIO_hdr.h"


int flag = 0;
int count = 0;

/*#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif*/

void EXTI1_IRQHandler(void){

	if(EXTI->PR & (HIGH << 1) !=0){
		pinWrite(PORTD,12);
		EXTI->PR |= (HIGH << 1); 															//clear pin
	}
}

int main(void)
{

//GPIO INIT
	//Configured Port D Pin 9 as output			(PD9)
	GPIO_TYPE GpioOutput;

				GpioOutput.port = PORTD;
				GpioOutput.pin  = 9;
				GpioOutput.mode_type = OUTPUT_MODE;

				gpioInit(GpioOutput);

	//Configured Port D Pin 10 as input			(PD10)
	GPIO_TYPE GpioInput;

				GpioInput.port = PORTA;
				GpioInput.pin = 1;
				GpioInput.mode_type = INTERRUPT_FT;

				gpioInit(GpioInput);

	//Configured port D pin 12 as output

	GPIO_TYPE GpioOutputLed12;

				GpioOutput.port = PORTD;
				GpioOutput.pin  = 12;
				GpioOutput.mode_type = OUTPUT_MODE;

				gpioInit(GpioOutputLed12);

	// SYSCNF & EXTIConfig
	/*SYS_CFG	intConfig;
	EXTI_Config	extiConfig;*/


	//RCC->APB2ENR |= (HIGH << 14);
	SYSCFG->EXTICR[0] &= ~SYSCFG_EXTICR1_EXTI1;
	SYSCFG->EXTICR[0] |= SYSCFG_EXTICR1_EXTI1_PA;

	//	SETTING PRIORITY AND ENABLING EXTI
	NVIC_SetPriority(EXTI1_IRQn, 7);
	NVIC_EnableIRQ(EXTI1_IRQn);


	//sysIntConfig(GpioInput, intConfig.pSYSConfig, extiConfig.pEXTIxIntConfig);






    /* Loop forever */
	for(;;){
		pinWrite(PORTD,9);
		if(flag){
			void EXTI1_IRQHandler(void);
			DELAY(10);
			flag = 0;
		}else {flag = 1;}
	}


} //END OF MAIN


